# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob

APP = ['nenra.py']
APP_NAME = "NENRA"
DATA_FILES = [
    ('images', glob('images/*.*')),
]

OPTIONS = {
    'argv_emulation': True,

    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Nen Restaurant Automotion",
        'CFBundleIdentifier': "com.nen.osx.nenra",
        'CFBundleVersion': "1.1.0",
        'CFBundleShortVersionString': "1.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2015, Namık ERDOĞAN, All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
