# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gelirtablo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog4(object):
    def setupUi(self, Dialog4):
        Dialog4.setObjectName("Dialog4")
        Dialog4.resize(911, 788)
        self.dateEdit = QtWidgets.QDateEdit(Dialog4)
        self.dateEdit.setGeometry(QtCore.QRect(10, 40, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label = QtWidgets.QLabel(Dialog4)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog4)
        self.pushButton.setGeometry(QtCore.QRect(10, 230, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog4)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 370, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(Dialog4)
        self.tableWidget.setGeometry(QtCore.QRect(180, 10, 711, 761))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog4)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 590, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog4)
        QtCore.QMetaObject.connectSlotsByName(Dialog4)

    def retranslateUi(self, Dialog4):
        _translate = QtCore.QCoreApplication.translate
        Dialog4.setWindowTitle(_translate("Dialog4", "Gelir Tablosu"))
        self.dateEdit.setDisplayFormat(_translate("Dialog4", "MM.yyyy"))
        self.label.setText(_translate("Dialog4", " Tarih"))
        self.pushButton.setText(_translate("Dialog4", "Gelir Raporu"))
        self.pushButton_2.setText(_translate("Dialog4", "PDF Rapor "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog4", "Açıklama"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog4", "Kod"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog4", "Tutar"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog4", "."))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog4", "."))
        self.pushButton_3.setText(_translate("Dialog4", "Güncelle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog4 = QtWidgets.QDialog()
    ui = Ui_Dialog4()
    ui.setupUi(Dialog4)
    Dialog4.show()
    sys.exit(app.exec_())
